// Getting Element
// Input fields
const namE = document.getElementById('name')
const fname = document.getElementById('fname')
const phno = document.getElementById('phno')
const nicno = document.getElementById('nicno')
const nationality = document.getElementById('nation')
const religion = document.getElementById('religion')
const mstatus = document.getElementById('mstatus')
const dob = document.getElementById('dob')
const address = document.getElementById('address')
const mail = document.getElementById('mail')
const ed1 = document.getElementById('ed1')
const ed1from = document.getElementById('ed1from')
const ed2 = document.getElementById('ed2')
const ed2from = document.getElementById('ed2from')
const job1 = document.getElementById('job1')
const job1where = document.getElementById('job1where')
const job1date = document.getElementById('job1date')
const job2 = document.getElementById('job2')
const job2where = document.getElementById('job2where')
const job2date = document.getElementById('job2date')
const job3 = document.getElementById('job3')
const job3where = document.getElementById('job3where')
const job3date = document.getElementById('job3date')
const skill1 = document.getElementById('skill1')
const skill1Range = document.getElementById('skill1range')
const skill2 = document.getElementById('skill2')
const skill2Range = document.getElementById('skill2range')
const skill3 = document.getElementById('skill3')
const skill3Range = document.getElementById('skill3range')
const skill4 = document.getElementById('skill4')
const skill4Range = document.getElementById('skill4range')
const skill5 = document.getElementById('skill5')
const skill5Range = document.getElementById('skill5range')
const lang1 = document.getElementById('lang1')
const lang2 = document.getElementById('lang2')
const hobby1 = document.getElementById('hb1')
const hobby2 = document.getElementById('hb2')
const resumePic = document.getElementById('picimg')

//buttons and divs
const genBtn = document.getElementById('generatebtn')
const editBtn = document.getElementById('editbtn')
const formDiv = document.getElementById('resumeForm')
const resumeDiv = document.getElementById('resumeGen')
const optjobDiv = document.getElementById('optjob')

// html resume fields

